# Generated by Django 5.2.6 on 2026-04-05 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "complaint_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الشكوى"
                    ),
                ),
                (
                    "complainant_name",
                    models.CharField(max_length=255, verbose_name="اسم المشتكي"),
                ),
                (
                    "complainant_id_number",
                    models.CharField(max_length=20, verbose_name="رقم الهوية"),
                ),
                (
                    "complainant_phone",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف"),
                ),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="المنطقة/المخيم"),
                ),
                ("original_text", models.TextField(verbose_name="النص الأصلي للشكوى")),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملخص الذكاء الاصطناعي"
                    ),
                ),
                (
                    "ai_category",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القطاع المستهدف",
                    ),
                ),
                (
                    "ai_severity",
                    models.IntegerField(
                        choices=[
                            (1, "عادي"),
                            (2, "متوسط"),
                            (3, "هام"),
                            (4, "عاجل"),
                            (5, "حرج"),
                        ],
                        default=1,
                        verbose_name="مستوى الخطورة الآلي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("IN_PROGRESS", "قيد المعالجة"),
                            ("RESOLVED", "محلول"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="حالة الشكوى",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_complaints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الباحث المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "شكوى",
                "verbose_name_plural": "الشكاوى",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_title",
                    models.CharField(max_length=255, verbose_name="الحدث"),
                ),
                (
                    "action_description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجراء الشكوى",
                "verbose_name_plural": "سجل إجراءات الشكاوى",
                "ordering": ["-action_date"],
            },
        ),
    ]
