# Generated by Django 5.2.6 on 2026-04-05 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={},
        ),
        migrations.AlterModelOptions(
            name="complaintaction",
            options={},
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="submitted_by",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="ai_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="ai_severity",
            field=models.IntegerField(
                choices=[
                    (1, "Low"),
                    (2, "Normal"),
                    (3, "Important"),
                    (4, "Urgent"),
                    (5, "Critical"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complainant_id_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complainant_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complainant_phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="original_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="region",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="complaintaction",
            name="action_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaintaction",
            name="action_title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="complaintaction",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("for_admin_only", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
