# Generated by Django 5.2.6 on 2026-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_alter_notification_options_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="camp_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="case_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
